# Generated by Django 3.2.6 on 2021-08-30 11:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Meeting_date', models.DateTimeField()),
                ('Description', models.TextField(default='', null=True)),
                ('Cancel_reason', models.TextField(default='', null=True)),
                ('Meeting_type', models.CharField(choices=[('T', 'Test'), ('T', 'Job interview')], default=None, max_length=1, null=True)),
                ('Meeting_status', models.CharField(choices=[('P', 'Upcoming'), ('C', 'Cancelled'), ('N', 'Confirmed')], default='U', max_length=1)),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'Calendar',
            },
        ),
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default=None, max_length=25)),
                ('Surname', models.CharField(default=None, max_length=25)),
                ('Birthdate', models.DateField()),
                ('Application_date', models.DateField(auto_now_add=True)),
                ('Phone_number', models.CharField(max_length=13, null=True)),
                ('Sex', models.CharField(choices=[('U', 'Unsure'), ('F', 'Female'), ('M', 'Male')], default=None, max_length=1, null=True)),
                ('Email_address', models.EmailField(max_length=50, null=True)),
                ('CV', models.TextField(default='')),
                ('Motivation_letter', models.TextField(default='')),
                ('Hired', models.CharField(choices=[('P', 'In process'), ('Y', 'Yes'), ('N', 'No')], default='', max_length=10)),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidates',
            },
        ),
        migrations.CreateModel(
            name='Candidates_Role',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default=None, max_length=25)),
            ],
            options={
                'verbose_name': 'Candidate role',
                'verbose_name_plural': 'Candidates roles',
            },
        ),
        migrations.CreateModel(
            name='Recruitment_Meetings',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Hard_skills', models.TextField(default='', null=True)),
                ('Soft_skills', models.TextField(default='', null=True)),
                ('Grade', models.DecimalField(decimal_places=0, max_digits=2, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('Notes', models.TextField(default='', null=True)),
                ('Date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'meeting',
                'verbose_name_plural': 'Recruitment meetings',
            },
        ),
        migrations.CreateModel(
            name='Recruitment_Process',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Stage', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], default='', max_length=1)),
                ('ID_Candidates', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='back.candidates', verbose_name='Candidate')),
                ('ID_Candidates_Role', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='back.candidates_role', verbose_name='Candidate role')),
            ],
            options={
                'verbose_name': 'Process',
                'verbose_name_plural': 'Recruitment process',
            },
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Points', models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('Check_out_date', models.DateField(auto_now_add=True)),
                ('ID_Recruitment_Process', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='back.recruitment_process', verbose_name='Candidate and his role')),
            ],
            options={
                'verbose_name': 'test',
                'verbose_name_plural': 'Tests',
            },
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default='', max_length=25, null=True)),
                ('Surname', models.CharField(default='', max_length=25, null=True)),
                ('Birthdate', models.DateField(null=True)),
                ('Login', models.CharField(max_length=32, null=True)),
                ('Password', models.CharField(default='', max_length=32)),
                ('Email_address', models.EmailField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'worker',
                'verbose_name_plural': 'Workers',
            },
        ),
        migrations.CreateModel(
            name='Workers_Role',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=40, null=True, unique=True, verbose_name='Role')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Workers roles',
            },
        ),
        migrations.DeleteModel(
            name='Departments',
        ),
        migrations.DeleteModel(
            name='Employees',
        ),
        migrations.AddField(
            model_name='workers',
            name='ID_Workers_Role',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='back.workers_role', verbose_name='Role'),
        ),
        migrations.AddField(
            model_name='tests',
            name='ID_Workers',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='back.workers', verbose_name='Worker'),
        ),
        migrations.AddField(
            model_name='recruitment_meetings',
            name='ID_Recruitment_Process',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='back.recruitment_process', verbose_name='Recruitment process'),
        ),
        migrations.AddField(
            model_name='recruitment_meetings',
            name='ID_Workers',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='back.workers', verbose_name='Worker'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='ID_Recruitment_Process',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='back.recruitment_process', verbose_name='Recruitment process'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='ID_Workers',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='back.workers', verbose_name='Worker'),
        ),
    ]
